---
# tasks file for nginx_proxy
- name: Установка nginx
  ansible.builtin.shell: |
    apt install nginx -y

- name: Запуск прокси nginx
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: "Nginx Reloader"

- name: Установка haproxy
  ansible.builtin.shell: |
    apt install haproxy -y
  
- name: Запуск прокси haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
 
- name: Запуск haproxy
  ansible.builtin.shell: |
    systemctl restart haproxy
 
