linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    nginx_p: #Имя подгруппы хостов
     hosts: #Узлы группы
       vm1: #Имя машины
         ansible_host: 89.169.164.250 #Адрес машины
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm2: #Имя машины
          ansible_host: 158.160.25.226 #Адрес машины
        vm3: #Имя машины
          ansible_host: 158.160.10.252 #Адрес машины
    zabbix: #Имя подгруппы хостов
     hosts: #Узлы группы
       vm4: #Имя машины
         ansible_host: 158.160.12.119 #Адрес машины
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "root"
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения
