---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx_p: #Имя подгруппы хостов
     hosts: #Узлы группы
       vm1: #Имя машины
         ansible_host: 62.84.122.156 #Адрес машины
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm2: #Имя машины
          ansible_host: 51.250.28.48 #Адрес машины
        vm3: #Имя машины
          ansible_host: 51.250.101.20 #Адрес машины
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "root"
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения
