---
# tasks file for nginx_proxy
- name: Установка php
  shell: 'apt install php-fpm php-pgsql php-intl php-gd php-xml php-mbstring -y'

- name: Установка nginx
  ansible.builtin.shell: |
    apt install nginx -y

- name: Запуск прокси nginx
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: "Nginx Reloader"

- name: Установка MediaWiki
  ansible.builtin.shell: |
    cd /var/www/ &&
    wget https://releases.wikimedia.org/mediawiki/1.42/mediawiki-1.42.1.tar.gz &&
    tar -xvzf mediawiki-1.42.1.tar.gz &&
    mv mediawiki-1.42.1 mediawiki &&
    chown -R www-data:www-data /var/www/mediawiki &&
    chmod -R 755 /var/www/mediawiki

- name: Установка Postgres 17
  ansible.builtin.shell:
    sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' &&
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg &&
    apt update -y &&
    apt-get -y install postgresql postgresql-contrib
