---
# tasks file for nginx_custom
- name: Подмена веб-страницы vm2
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'vm-2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm2
  notify: "Nginx Reloader"
- name: Подмена веб-страницы vm3
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  when: "'vm-3' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm3
  notify: "Nginx Reloader"
